SET ECHO OFF FEEDBACK OFF VERIFY OFF HEADING OFF PAGESIZE 0
SET LINESIZE 32767 TRIMSPOOL ON LONG 100000000 LONGCHUNKSIZE 32767

SPOOL sql-monitor-report.html

SELECT DBMS_SQLTUNE.REPORT_SQL_MONITOR(
         sql_id       => 'REPLACE_WITH_SQL_ID',
         type         => 'ACTIVE',
         report_level => 'ALL') AS report
FROM   dual;

SPOOL OFF
